# -*- coding: utf-8 -*-
"""ejercicios 1 y 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-WJ01qq5RPySZ6KshJD8Knb2EXFrWTl
"""
#soy un nuevo comentario
print('Hola mundo')

print("ingrese el nombre")

nombre = input()
edad = int(input("ingrese la edad"))
promedio = float(input("ingrese el promedio"))

numero1 = int(input("ingrasa un numero "))
numero2 = int(input("ingrese otro numero"))

suma = numero1 + numero2

print("la suma es", suma)
#soy un segundo comentario